openapi: 3.0.0
info:
  version: "1.0.0"
  title: Inventory API
tags:
  - name: categories
    description: Everything about categories
  - name: products
    description: Everything about products
paths:
  /products:
    get:
      tags:
        - products
      summary: Get all products
      responses:
        '200':
          description: All products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/{id}:
    get:
      tags:
        - products
      summary: Get product by id
      parameters:
        - in: path
          name: id
          required: true
          description: Product id
          schema:
            type: integer
      responses:
        '200':
          description: Product by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /products/search:
    post:
      tags:
        - products
      summary: Search for products
      responses:
        '200':
          description: Products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - searchDescription
                - searchMinPrice
                - searchMaxPrice
              properties:
                searchDescription:
                  type: string
                searchMinPrice:
                  type: number
                searchMaxPrice:
                  type: number
        description: The category to create.
  /categories:
    get:
      tags:
        - categories
      summary: Get all categories
      responses:
        '200':
          description: All categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
  /categories/{id}:
    get:
      tags:
        - categories
      summary: Get category by id
      parameters:
        - in: path
          name: id
          required: true
          description: Category id
          schema:
            type: integer
      responses:
        '200':
          description: Category by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
    delete:
      tags:
        - categories
      summary: Delete category by id
      parameters:
        - in: path
          name: id
          required: true
          description: Category Id
          schema:
            type: integer
      responses:
        '200':
          description: Api Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
components:
    schemas:
      Category:
        type: object
        properties:
          id:
            type: integer
            format: int64
          name:
            type: string
          products:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                name:
                  type: string
                price:
                  type: number
                details:
                  type: string
      Product:
        type: object
        properties:
          id:
            type: integer
            format: int64
          name:
            type: string
          price:
            type: number
          category:
            type: object
            properties:
              id:
                type: integer
                format: int64
              name:
                type: string
          details:
            type: string
      ApiResponse:
        type: object
        properties:
          message:
            type: string