server:
  port: 8080
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

zuul:
  ignoredServices: "*"
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    authorization-service: /auth/**
    user-service: /user-api/**
    webshop-api: /api/**

security:
  oauth2:
    resource:
      user-info-uri: http://authorization-service:8080/me
