spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://user-db:3306/users?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: usersUser
    password: supersecret

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"


security:
  oauth2:
    resource:
      user-info-uri: http://authorization-service:8080/me