spring:
  application:
      name: category-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://category-db:3306/categories?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: catUser
    password: supersecret

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
