server:
    port: 8089

eureka:
    instance:
        hostname: discovery-service
    client:
        registerWithEureka: false
        fetchRegistry: false
    server:
        waitTimeInMsWhenSyncEmpty: 0
    service-url:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/