spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://product-db:3306/products?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: prodUser
    password: supersecret
