spring:
  application:
    name: webshop-api

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health

hystrix:
  shareSecurityContext: true

security:
  oauth2:
    resource:
      user-info-uri: http://authorization-service:8080/me