package de.hska.iwi.vslab.categoryservice;

import org.springframework.web.bind.annotation.*;
import org.springframework.beans.factory.annotation.Autowired;

@RestController
public class CategoryController {

    @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
    private CategoryRepository categoryRepository;

    @RequestMapping(value="/categories", method= RequestMethod.GET)
    public Iterable<Category> getAllCategories() {
        return categoryRepository.findAll();
    }

    @RequestMapping(value="/categories", method= RequestMethod.POST)
    public String createNewCategory(@RequestParam String categoryName) {
        Category newCat = new Category();
        int[] products = {};
        newCat.setName(categoryName);
        newCat.setProducts(products);
        categoryRepository.save(newCat);
        return "saved new category";
    }

    @RequestMapping(value="/categories/{id}", method= RequestMethod.GET)
    public String getCategoryById(@PathVariable("id") String id) {
        return "Hallo World!";
    }

    @RequestMapping(value="/categories/{id}", method= RequestMethod.DELETE)
    public String deleteCategoryById(@PathVariable("id") String id) {
        return "Hallo World!";
    }
}